name: Deploy to Easypanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Easypanel Deployment
        run: |
          curl -X POST "${{ secrets.EASY_PANEL_URL }}"